#[macro_use] mod imports; use imports::*;

x!{absolute}
x!{bound_value}
x!{clear_flags}
x!{control_group}
x!{control_style}
x!{control_type}
x!{controller_get_parameter}
x!{controller_normalize}
x!{controller_send_automation}
x!{controller_set_parameter}
x!{default_value}
x!{display}
x!{extend}
x!{extend_range}
x!{extreme_values}
x!{get_modulation}
x!{get_set_modulation}
x!{get_value}
x!{get_value_type}
x!{limit_range}
x!{metadata}
x!{modulation}
x!{morph}
x!{moverate}
x!{normalize}
x!{notation}
x!{param}
x!{parameter}
x!{parameter_controller}
x!{parameter_dependency}
x!{pdata}
x!{pval}
x!{set_modulation}
x!{set_value}
x!{snap}
x!{temposync}
x!{user_data}
x!{runtime}
