crate::ix!();

enhanced_enum![
    SceneParam {
        Pitch,
        Octave,
        FmDepth,
        FmSwitch,
        Drift,
        NoiseColour,
        KeytrackRoot,
        OscSolo,
        LevelO1,
        LevelO2,
        LevelO3,
        LevelNoise,
        LevelRing12,
        LevelRing23,
        LevelPfg,
        MuteO1,
        MuteO2,
        MuteO3,
        MuteNoise,
        MuteRing12,
        MuteRing23,
        SoloO1,
        SoloO2,
        SoloO3,
        SoloNoise,
        SoloRing12,
        SoloRing23,
        RouteO1,
        RouteO2,
        RouteO3,
        RouteNoise,
        RouteRing12,
        RouteRing23,
        VcaLevel,
        PitchBendRangeDown,
        PitchBendRangeUp,
        VcaVelsense,
        PolyMode,
        PolyLimit,
        Portamento,
        Volume,
        Pan,
        Width,
        SendLevelA,
        SendLevelB,
        F2CutoffIsOffset,
        F2LinkResonance,
        Feedback,
        FilterBlockConfiguration,
        FilterBalance,
        LowCut,
    }
];

rt![SceneParam];

impl ParameterInterface for SceneParam {
    fn control_group(&self) -> ControlGroup { ControlGroup::Global } 
    /* TODO */
}

impl SceneParam {

    pub fn new_runtime() -> SceneParamArrayRT {
        SceneParamArrayRT::new_with( |x| match x {
            SceneParam::Pitch                    => SceneParamRT::new(SceneParam::Pitch),
            SceneParam::Octave                   => SceneParamRT::new(SceneParam::Octave),
            SceneParam::FmDepth                  => SceneParamRT::new(SceneParam::FmDepth),
            SceneParam::FmSwitch                 => SceneParamRT::new(SceneParam::FmSwitch),
            SceneParam::Drift                    => SceneParamRT::new(SceneParam::Drift),
            SceneParam::NoiseColour              => SceneParamRT::new(SceneParam::NoiseColour),
            SceneParam::KeytrackRoot             => SceneParamRT::new(SceneParam::KeytrackRoot),
            SceneParam::OscSolo                  => SceneParamRT::new(SceneParam::OscSolo),
            SceneParam::LevelO1                  => SceneParamRT::new(SceneParam::LevelO1),
            SceneParam::LevelO2                  => SceneParamRT::new(SceneParam::LevelO2),
            SceneParam::LevelO3                  => SceneParamRT::new(SceneParam::LevelO3),
            SceneParam::LevelNoise               => SceneParamRT::new(SceneParam::LevelNoise),
            SceneParam::LevelRing12              => SceneParamRT::new(SceneParam::LevelRing12),
            SceneParam::LevelRing23              => SceneParamRT::new(SceneParam::LevelRing23),
            SceneParam::LevelPfg                 => SceneParamRT::new(SceneParam::LevelPfg),
            SceneParam::MuteO1                   => SceneParamRT::new(SceneParam::MuteO1),
            SceneParam::MuteO2                   => SceneParamRT::new(SceneParam::MuteO2),
            SceneParam::MuteO3                   => SceneParamRT::new(SceneParam::MuteO3),
            SceneParam::MuteNoise                => SceneParamRT::new(SceneParam::MuteNoise),
            SceneParam::MuteRing12               => SceneParamRT::new(SceneParam::MuteRing12),
            SceneParam::MuteRing23               => SceneParamRT::new(SceneParam::MuteRing23),
            SceneParam::SoloO1                   => SceneParamRT::new(SceneParam::SoloO1),
            SceneParam::SoloO2                   => SceneParamRT::new(SceneParam::SoloO2),
            SceneParam::SoloO3                   => SceneParamRT::new(SceneParam::SoloO3),
            SceneParam::SoloNoise                => SceneParamRT::new(SceneParam::SoloNoise),
            SceneParam::SoloRing12               => SceneParamRT::new(SceneParam::SoloRing12),
            SceneParam::SoloRing23               => SceneParamRT::new(SceneParam::SoloRing23),
            SceneParam::RouteO1                  => SceneParamRT::new(SceneParam::RouteO1),
            SceneParam::RouteO2                  => SceneParamRT::new(SceneParam::RouteO2),
            SceneParam::RouteO3                  => SceneParamRT::new(SceneParam::RouteO3),
            SceneParam::RouteNoise               => SceneParamRT::new(SceneParam::RouteNoise),
            SceneParam::RouteRing12              => SceneParamRT::new(SceneParam::RouteRing12),
            SceneParam::RouteRing23              => SceneParamRT::new(SceneParam::RouteRing23),
            SceneParam::VcaLevel                 => SceneParamRT::new(SceneParam::VcaLevel),
            SceneParam::PitchBendRangeDown       => SceneParamRT::new(SceneParam::PitchBendRangeDown),
            SceneParam::PitchBendRangeUp         => SceneParamRT::new(SceneParam::PitchBendRangeUp),
            SceneParam::VcaVelsense              => SceneParamRT::new(SceneParam::VcaVelsense),
            SceneParam::PolyMode                 => SceneParamRT::new(SceneParam::PolyMode),
            SceneParam::PolyLimit                => SceneParamRT::new(SceneParam::PolyLimit),
            SceneParam::Portamento               => SceneParamRT::new(SceneParam::Portamento),
            SceneParam::Volume                   => SceneParamRT::new(SceneParam::Volume),
            SceneParam::Pan                      => SceneParamRT::new(SceneParam::Pan),
            SceneParam::Width                    => SceneParamRT::new(SceneParam::Width),
            SceneParam::SendLevelA               => SceneParamRT::new(SceneParam::SendLevelA),
            SceneParam::SendLevelB               => SceneParamRT::new(SceneParam::SendLevelB),
            SceneParam::F2CutoffIsOffset         => SceneParamRT::new(SceneParam::F2CutoffIsOffset),
            SceneParam::F2LinkResonance          => SceneParamRT::new(SceneParam::F2LinkResonance),
            SceneParam::Feedback                 => SceneParamRT::new(SceneParam::Feedback),
            SceneParam::FilterBlockConfiguration => SceneParamRT::new(SceneParam::FilterBlockConfiguration),
            SceneParam::FilterBalance            => SceneParamRT::new(SceneParam::FilterBalance),
            SceneParam::LowCut                   => SceneParamRT::new(SceneParam::LowCut),
        })
    }
}
