#![feature(box_syntax)]
#![feature(box_patterns)]

#[macro_use] mod imports; use imports::*;

x![calc];
x![calc_envelope];
x![calc_keytrack];
x![calc_levels];
x![calc_lfo];
x![calc_modsources];
x![calc_mpe];
x![calc_pan];
x![calc_pitch];
x![calc_poly_aftertouch];
x![calc_route];
x![create];
x![do_noise];
x![do_osc];
x![do_ring];
x![drop];
x![filter];
x![filterblock];
x![gen_runtime];
x![get];
x![init];
x![init_attack];
x![init_modsource];
x![init_portasrc];
x![note_shift];
x![portamento];
x![process];
x![release];
x![runtime];
x![set_qfb];
x![state];
x![voice];
x![sync_from_qfb];
x![toggle];
x![toggle_filter];
x![toggle_fm];
x![toggle_osc];
x![toggle_solo];
x![voice_runtime];
