#[macro_use] mod imports; use imports::*;

x!{attack}
x!{attack_shape_noise}
x!{attack_shape_sine}
x!{attack_shape_snh}
x!{attack_shape_stepseq}
x!{attack_shape_tri}
x!{attack_shapes}
x!{bend}
x!{constants}
x!{get}
x!{init}
x!{lfo}
x!{modsource}
x!{param}
x!{phase_over_one}
x!{phaseincrement}
x!{phaseslider}
x!{process}
x!{process_shape_stepseq}
x!{process_shapes}
x!{release}
x!{set}
x!{update}
x!{update_envelope}

xt!{test_attack}
xt!{test_attack_shape_noise}
xt!{test_attack_shape_sine}
xt!{test_attack_shape_snh}
xt!{test_attack_shape_stepseq}
xt!{test_attack_shape_tri}
xt!{test_attack_shapes}
xt!{test_bend}
xt!{test_get}
xt!{test_init}
xt!{test_phase_over_one}
xt!{test_phaseslider}
xt!{test_process}
xt!{test_process_shape_stepseq}
xt!{test_process_shapes}
xt!{test_release}
xt!{test_set}
xt!{test_update}
xt!{test_update_envelope}
