#[macro_use] mod imports; use imports::*;

x![attack];
x![attack_shapes];
x![bend];
x![constants];
x![get];
x![init];
x![lfo];
x![modsource];
x![param];
x![phase_over_one];
x![phaseslider];
x![process];
x![process_shapes];
x![release];
x![set];
x![stepsequencer];
x![update];
x![update_envelope];
